apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sdf-data-supercdms-ro
spec: 
  storageClassName: sdf-data-supercdms
  accessModes: 
    - ReadOnlyMany
  resources:
    requests: 
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sdf-group-supercdms-ro
spec: 
  storageClassName: sdf-group-supercdms
  accessModes: 
    - ReadOnlyMany
  resources:
    requests: 
      storage: 1Gi
